### ISSUE TITLE
Some corrections

### ISSUE THREAD

**Issue by dirichs** [daviddengcn/lockfreepool#1]
Hi, I like your lock free pool implementation; it is concise, straight forward and does not need any dependencies. Thanks for making it available!

However, I noted two issues with the code that leads to `IndexOutOfBoundException` thrown by `AtomicReferenceArray`. The first issue is in ObjectPool.java, line 61:
 `               if (n == objects.length()) {
`
This should be
`                if (n == objects.length() - 1) {
`
since otherwise, a subsequent access to the `AtomicReferenceArray` may try to set index n == objects.length(), which causes the `IndexArrayOutOfBoundsException` thrown immediately.

The second problem is in ObjectPool.java, line 64: Here, the code should `return` from the method and not stay in the loop.

Apart from that, I could spot no errors.

**Comment by daviddengcn** [comment]
Thanks for pointing out the bug and they have been fixed.

But the fix to the first issue is different from what you suggest. Noticing top is the place of the first **free** space in objects, the `if (n == objects.length()) {` is actually correct but the latter `compareAndSet` should use `n` instead of `n+1`. Feel free to comment if I'm wrong about anything.

Thanks again for bringing back to this project I haven't touched for years.

**Comment by dirichs** [comment]
Yes, it is possible to do so and seeing top as first free space this would also be a correct approach. However, note that alloc() must be changed accordingly: Here,

            E e = objects.getAndSet(n, null);

is to be replaced with

            E e = objects.getAndSet(n - 1, null);

since the topmost instance is in index n-1 if n is the first free index. Use this line together with your suggestion and all works well - I have tested it.

Am Fr, 26. Mär 2021, um 15:15, schrieb Yi Deng:

**Comment by daviddengcn** [comment]
You are right again. I should've made a unit test here. But I don't have the convenient running environment as the time I created the project.

Bug fixed.
